version: "3.8"

services:
  app:
    image: "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: ${PROFILE}
        DB_ENDPOINT: ${DB_ENDPOINT}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}