version: '3.8'
services:
  app:
    image: "${DOCKER_IMAGE}:${DOCKER_TAG}"
    networks:
      - app_network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "0.20"
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  app_network:
    driver: overlay
