apiVersion: apps/v1
kind: Deployment
metadata:
  name: manishboard-backend-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/officialmanishkr98/manishboard-backend:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      # imagePullSecrets:
      # - name: ghcr-secret